name: BuildNotifier-Folia
version: '${project.version}'
main: lol.hyper.buildnotifier.folia.BuildNotifierFolia
author: hyperdefined
api-version: 1.19
description: "Automatically check for Paper/Waterfall/Velocity/Folia updates."
folia-supported: true
permissions:
  buildnotifier.message:
    default: op
    description: "If players have this, they will receive messages on join about server updates."
